### ISSUE TITLE
wrap actions/setup-node@v3

### ISSUE THREAD

**Issue by davidkhala** [davidkhala/ci-cd-utils#6]
```
- uses: actions/setup-node@v3
  with:
        check-latest: true
- uses: ScribeMD/rootless-docker@main
  name: Use Docker in rootless mode.
```
Wrap this into single line
